const descriptions=["Vista principal de la casa","Fachada de la propiedad","Área social","Vista interior","Cocina italiana","Ambiente familiar","Terraza con vista al Ávila","Espacio para reuniones","Habitación","Baño","Habitación principal","Vestier","Jacuzzi","Family room","Espacios interiores","Área complementaria","Sótano","Vista desde la propiedad","Detalles de la casa","Entorno residencial"];
const images=descriptions.map((alt,index)=>({src:`fk8${String.fromCharCode(97+index)}.png`,alt}));
let currentIndex=0;
const mainImage=document.querySelector("#mainImage"),container=document.querySelector("#thumbnailContainer"),lightbox=document.querySelector("#lightbox"),lightboxImage=document.querySelector("#lightboxImage");
function updateImage(index){currentIndex=index;mainImage.src=images[index].src;mainImage.alt=images[index].alt;if(lightbox.classList.contains("active")){lightboxImage.src=images[index].src;lightboxImage.alt=images[index].alt}document.querySelectorAll(".thumbnail").forEach((thumb,i)=>{thumb.classList.toggle("active",i===index);thumb.setAttribute("aria-current",i===index?"true":"false")})}
function buildGallery(){const fragment=document.createDocumentFragment();images.forEach((image,index)=>{const button=document.createElement("button"),img=document.createElement("img");button.className="thumbnail";button.type="button";button.setAttribute("aria-label",`Ver imagen ${index+1}`);img.src=image.src;img.alt=image.alt;img.loading=index<5?"eager":"lazy";button.appendChild(img);button.addEventListener("click",()=>updateImage(index));fragment.appendChild(button)});container.replaceChildren(fragment)}
function openLightbox(){lightboxImage.src=images[currentIndex].src;lightboxImage.alt=images[currentIndex].alt;lightbox.classList.add("active");lightbox.setAttribute("aria-hidden","false");document.body.style.overflow="hidden"}
function closeLightbox(){lightbox.classList.remove("active");lightbox.setAttribute("aria-hidden","true");document.body.style.overflow=""}
function move(direction){updateImage((currentIndex+direction+images.length)%images.length)}
buildGallery();updateImage(0);
mainImage.addEventListener("click",openLightbox);document.querySelector("#openLightboxBtn").addEventListener("click",openLightbox);document.querySelector("#closeLightboxBtn").addEventListener("click",closeLightbox);document.querySelector("#nextBtn").addEventListener("click",()=>move(1));document.querySelector("#prevBtn").addEventListener("click",()=>move(-1));lightbox.addEventListener("click",event=>{if(event.target===lightbox)closeLightbox()});document.addEventListener("keydown",event=>{if(!lightbox.classList.contains("active"))return;if(event.key==="Escape")closeLightbox();if(event.key==="ArrowRight")move(1);if(event.key==="ArrowLeft")move(-1)});
